/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM_OLD;

import IHM_OLD.Representant;
import IHM_OLD.Prospect;
import IHM_OLD.Client;

/**
 *
 * @author ldescamps
 */
public class RepCliProsp extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public RepCliProsp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneRepCliProsp = new javax.swing.JTabbedPane();
        jPanelRep = new javax.swing.JPanel();
        jButtonAddRep = new javax.swing.JButton();
        jButtonModRep = new javax.swing.JButton();
        jButtonDelRep = new javax.swing.JButton();
        jButtonCloseRep = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextFieldNumRep = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldLastNameRep = new javax.swing.JTextField();
        jTextFieldCityRep = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanelCli = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldNameSocCli = new javax.swing.JTextField();
        jTextFieldlastNameContCli = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldFirstNameContcli = new javax.swing.JTextField();
        jTextFieldAddrCli = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldPostCodeCli = new javax.swing.JTextField();
        jTextFieldCitycli = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldCountryCli = new javax.swing.JTextField();
        jTextFieldPhoneCli = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldMailCli = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldNumCli = new javax.swing.JTextField();
        jTextFieldSiretCli = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldNumRepCli = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldNbrComm = new javax.swing.JTextField();
        jButtonAddClient = new javax.swing.JButton();
        jButtonModClient = new javax.swing.JButton();
        jButtonDelClient = new javax.swing.JButton();
        jButtonCloseClient = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelProsp = new javax.swing.JPanel();
        jButtonAddProsp = new javax.swing.JButton();
        jButtonModProsp = new javax.swing.JButton();
        jButtonDelProsp = new javax.swing.JButton();
        jButtonCloseProsp = new javax.swing.JButton();
        jButtonConvertProsp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TOUTBOIS Trop");
        setResizable(false);

        jButtonAddRep.setText("Ajouter");
        jButtonAddRep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddRepMouseClicked(evt);
            }
        });
        jButtonAddRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddRepActionPerformed(evt);
            }
        });

        jButtonModRep.setText("Modifier");

        jButtonDelRep.setText("Supprimer");

        jButtonCloseRep.setText("Fermer");
        jButtonCloseRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseRepActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "N° Représentant", "Nom", "Prénom", "Code Postal", "Ville", "Taux de comm.", "Fixe brut"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable3);

        jTextFieldNumRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumRepActionPerformed(evt);
            }
        });

        jLabel1.setText("N° Repres.");

        jLabel2.setText("Nom");

        jLabel6.setText("Ville");

        javax.swing.GroupLayout jPanelRepLayout = new javax.swing.GroupLayout(jPanelRep);
        jPanelRep.setLayout(jPanelRepLayout);
        jPanelRepLayout.setHorizontalGroup(
            jPanelRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRepLayout.createSequentialGroup()
                .addGroup(jPanelRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRepLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(jPanelRepLayout.createSequentialGroup()
                        .addGroup(jPanelRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRepLayout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addComponent(jButtonAddRep)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonModRep)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDelRep)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCloseRep))
                            .addGroup(jPanelRepLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(26, 26, 26)
                                .addComponent(jTextFieldNumRep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)
                                .addComponent(jTextFieldLastNameRep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(26, 26, 26)
                                .addComponent(jTextFieldCityRep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(236, 236, 236)))
                .addContainerGap())
        );
        jPanelRepLayout.setVerticalGroup(
            jPanelRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextFieldCityRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldLastNameRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextFieldNumRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(188, 188, 188)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddRep)
                    .addComponent(jButtonModRep)
                    .addComponent(jButtonDelRep)
                    .addComponent(jButtonCloseRep))
                .addContainerGap())
        );

        jTabbedPaneRepCliProsp.addTab("Représentants", jPanelRep);

        jLabel14.setText("N° client");

        jTextFieldNameSocCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameSocCliActionPerformed(evt);
            }
        });

        jLabel15.setText("Nom contact");

        jLabel16.setText("Prénom contact");

        jLabel17.setText("Adresse");

        jLabel18.setText("C.P.");

        jLabel19.setText("Ville");

        jLabel20.setText("Pays");

        jLabel21.setText("Téléphone");

        jLabel22.setText("Email");

        jTextFieldMailCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMailCliActionPerformed(evt);
            }
        });

        jLabel23.setText("Nom Société");

        jTextFieldNumCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumCliActionPerformed(evt);
            }
        });

        jTextFieldSiretCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSiretCliActionPerformed(evt);
            }
        });

        jLabel24.setText("SIRET");

        jLabel25.setText("N° Représ.");

        jTextFieldNumRepCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumRepCliActionPerformed(evt);
            }
        });

        jLabel26.setText("Nbr de commandes");

        jTextFieldNbrComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNbrCommActionPerformed(evt);
            }
        });

        jButtonAddClient.setText("Ajouter");
        jButtonAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddClientActionPerformed(evt);
            }
        });

        jButtonModClient.setText("Modifier");

        jButtonDelClient.setText("Supprimer");

        jButtonCloseClient.setText("Fermer");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N° Client", "Société", "Code Postal", "Ville", "Représentant"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelCliLayout = new javax.swing.GroupLayout(jPanelCli);
        jPanelCli.setLayout(jPanelCliLayout);
        jPanelCliLayout.setHorizontalGroup(
            jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCliLayout.createSequentialGroup()
                        .addGroup(jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23))
                        .addGap(26, 26, 26)
                        .addGroup(jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCliLayout.createSequentialGroup()
                                .addGroup(jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCountryCli, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCitycli, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelCliLayout.createSequentialGroup()
                                        .addGroup(jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldPostCodeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldlastNameContCli, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldFirstNameContcli, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldAddrCli, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldNumCli, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldNameSocCli, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(49, 49, 49)
                                        .addGroup(jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel26))))
                                .addGap(26, 26, 26)
                                .addGroup(jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldSiretCli, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNumRepCli, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNbrComm, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMailCli, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelCliLayout.createSequentialGroup()
                                .addComponent(jTextFieldPhoneCli, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jButtonAddClient)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonModClient)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDelClient)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCloseClient)))
                        .addGap(0, 53, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCliLayout.setVerticalGroup(
            jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldMailCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextFieldNameSocCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jTextFieldSiretCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldlastNameContCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumRepCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldFirstNameContcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNbrComm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldAddrCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldPostCodeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldCitycli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldCountryCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAddClient)
                        .addComponent(jButtonModClient)
                        .addComponent(jButtonDelClient)
                        .addComponent(jButtonCloseClient))
                    .addGroup(jPanelCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(jTextFieldPhoneCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jTabbedPaneRepCliProsp.addTab("Clients", jPanelCli);

        jButtonAddProsp.setText("Ajouter");
        jButtonAddProsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProspActionPerformed(evt);
            }
        });

        jButtonModProsp.setText("Modifier");

        jButtonDelProsp.setText("Supprimer");

        jButtonCloseProsp.setText("Fermer");

        jButtonConvertProsp.setText("Convertir vers client");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "N° Prospect", "Société", "Code Postal", "Ville", "Dernier représentant", "Dernière visite"
            }
        ));
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanelProspLayout = new javax.swing.GroupLayout(jPanelProsp);
        jPanelProsp.setLayout(jPanelProspLayout);
        jPanelProspLayout.setHorizontalGroup(
            jPanelProspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProspLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jButtonAddProsp)
                .addGap(18, 18, 18)
                .addComponent(jButtonModProsp)
                .addGap(18, 18, 18)
                .addComponent(jButtonDelProsp)
                .addGap(18, 18, 18)
                .addComponent(jButtonCloseProsp)
                .addGap(18, 18, 18)
                .addComponent(jButtonConvertProsp)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProspLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanelProspLayout.setVerticalGroup(
            jPanelProspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProspLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(299, 299, 299)
                .addGroup(jPanelProspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddProsp)
                    .addComponent(jButtonModProsp)
                    .addComponent(jButtonDelProsp)
                    .addComponent(jButtonCloseProsp)
                    .addComponent(jButtonConvertProsp))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPaneRepCliProsp.addTab("Prospects", jPanelProsp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneRepCliProsp)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneRepCliProsp)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSiretCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSiretCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSiretCliActionPerformed

    private void jTextFieldNumCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumCliActionPerformed

    private void jTextFieldMailCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMailCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMailCliActionPerformed

    private void jTextFieldNameSocCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameSocCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameSocCliActionPerformed

    private void jTextFieldNumRepCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumRepCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumRepCliActionPerformed

    private void jTextFieldNbrCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNbrCommActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNbrCommActionPerformed

    private void jButtonAddRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddRepActionPerformed
        // TODO add your handling code here:
        Representant repr = new Representant(new java.awt.Frame(),true);
        repr.setVisible(true);
                
    }//GEN-LAST:event_jButtonAddRepActionPerformed

    private void jButtonAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddClientActionPerformed
        // TODO add your handling code here:
        Client cli = new Client(new java.awt.Frame(),true);
        cli.setVisible(true);
    }//GEN-LAST:event_jButtonAddClientActionPerformed

    private void jButtonAddProspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProspActionPerformed
        // TODO add your handling code here:
        Prospect pro = new Prospect(new java.awt.Frame(),true);
        pro.setVisible(true);
    }//GEN-LAST:event_jButtonAddProspActionPerformed

    private void jButtonCloseRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseRepActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCloseRepActionPerformed

    private void jButtonAddRepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddRepMouseClicked
        
    }//GEN-LAST:event_jButtonAddRepMouseClicked

    private void jTextFieldNumRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumRepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumRepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RepCliProsp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RepCliProsp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RepCliProsp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RepCliProsp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RepCliProsp dialog = new RepCliProsp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddClient;
    private javax.swing.JButton jButtonAddProsp;
    private javax.swing.JButton jButtonAddRep;
    private javax.swing.JButton jButtonCloseClient;
    private javax.swing.JButton jButtonCloseProsp;
    private javax.swing.JButton jButtonCloseRep;
    private javax.swing.JButton jButtonConvertProsp;
    private javax.swing.JButton jButtonDelClient;
    private javax.swing.JButton jButtonDelProsp;
    private javax.swing.JButton jButtonDelRep;
    private javax.swing.JButton jButtonModClient;
    private javax.swing.JButton jButtonModProsp;
    private javax.swing.JButton jButtonModRep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelCli;
    private javax.swing.JPanel jPanelProsp;
    private javax.swing.JPanel jPanelRep;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPaneRepCliProsp;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextFieldAddrCli;
    private javax.swing.JTextField jTextFieldCityRep;
    private javax.swing.JTextField jTextFieldCitycli;
    private javax.swing.JTextField jTextFieldCountryCli;
    private javax.swing.JTextField jTextFieldFirstNameContcli;
    private javax.swing.JTextField jTextFieldLastNameRep;
    private javax.swing.JTextField jTextFieldMailCli;
    private javax.swing.JTextField jTextFieldNameSocCli;
    private javax.swing.JTextField jTextFieldNbrComm;
    private javax.swing.JTextField jTextFieldNumCli;
    private javax.swing.JTextField jTextFieldNumRep;
    private javax.swing.JTextField jTextFieldNumRepCli;
    private javax.swing.JTextField jTextFieldPhoneCli;
    private javax.swing.JTextField jTextFieldPostCodeCli;
    private javax.swing.JTextField jTextFieldSiretCli;
    private javax.swing.JTextField jTextFieldlastNameContCli;
    // End of variables declaration//GEN-END:variables
}
