/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author ldescamps
 */
public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    public Accueil() {
        initComponents();
        intialise();
       
    }
    //Affiche un logo au lieu de l'icone java
     private void intialise() {
            this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("LogoTronconeuse.png")));
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitre = new javax.swing.JLabel();
        jButtonRepCliProsp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelImage = new javax.swing.JLabel();
        jButtonQuitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TOUTBOIS Gestion");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabelTitre.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        jLabelTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitre.setText("TOUTBOIS");
        jPanel1.add(jLabelTitre);
        jLabelTitre.setBounds(250, 20, 272, 54);

        jButtonRepCliProsp.setText("Représentants / Clients / Prospection");
        jButtonRepCliProsp.setAlignmentY(0.0F);
        jButtonRepCliProsp.setRequestFocusEnabled(false);
        jButtonRepCliProsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRepCliProspActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRepCliProsp);
        jButtonRepCliProsp.setBounds(20, 430, 240, 23);

        jLabel2.setText("SARL TOUTBOIS ® 2016");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(660, 480, 140, 14);

        jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/grossiste-fournisseur-mobilierdejardin3.jpg"))); // NOI18N
        jPanel1.add(jLabelImage);
        jLabelImage.setBounds(150, 130, 500, 260);

        jButtonQuitter.setText("Quitter");
        jButtonQuitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonQuitterMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonQuitter);
        jButtonQuitter.setBounds(710, 430, 67, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRepCliProspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRepCliProspActionPerformed
        // TODO add your handling code here:
        RepCliProsp f = new RepCliProsp(new java.awt.Frame(),true);
        f.setVisible(true);
        
    }//GEN-LAST:event_jButtonRepCliProspActionPerformed

    private void jButtonQuitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonQuitterMouseClicked
        // TODO add your handling code here:
        
        //Quitter l'application
        System.exit(0); 
    }//GEN-LAST:event_jButtonQuitterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    //UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());  //Affichage sur le thème du systeme utilisé
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JButton jButtonRepCliProsp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
