/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import Tableau.TableauPersonaliseClient;
import Classe.Client;
import Utilitaire.*;
import java.awt.Font;
import static java.awt.Font.BOLD;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTextField;
import Tableau.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.table.TableModel;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author ldescamps
 */
public class RepCliProspOLD extends javax.swing.JDialog {

    /**
     * Creates new form RepCliProsp01
     */
    //Création d'une variable indiquant dans quel fenetre de menu on travail
        //Par défaut a l'ouverture menu "Représentant"
        char infoMenu = 'r';
       
    private final TableauPersonaliseClient tbP = new TableauPersonaliseClient();
    public class AddAjouter extends AbstractAction{

        public AddAjouter() {
            super("Enregistrer");
        }

        @Override
        public void actionPerformed(ActionEvent ae) {
            //tbP.ajouterClient(new Client("","Tamere","Trouduculdumonde","Ducon","3","","","","","","","","",""));
            tbP.ajouterClient(new Client(jTextFieldDenominationNomSociete.getText(), jTextFieldDenominationIdentifiant.getText(), jTextFieldAdresseNumeroRue.getText() ,jTextFieldAdresseComplement.getText(), 
            jTextFieldAdresseCP.getText(),jTextFieldAdresseVille.getText(), jTextFieldAdresseCedex.getText(),jComboBoxPays.getSelectedItem().toString(),jTextFieldContactNom.getText(),
                jTextFieldContactPrenom.getText(),jTextFieldContactTelephone1.getText(),jTextFieldContactTelephone2.getText(),jTextFieldContactFax.getText(),
                    jTextFieldContactMail.getText(),jTextFieldComplementSiret.getText(), jTextFieldComplementRepresentant.getText()));
            
        }
        
    }   
        
    public RepCliProspOLD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        System.out.println("Menu = "+ infoMenu);
               
        //Affichage en gras du menu affiché 
        //Par défaut à l'ouverture mise en gras du menu "Représentant"
        jMenuRepresentant.setFont(new Font("default", Font.BOLD,12));
       
        //Interdit la modification manuelle des champs à l'ouverture
        JTextField[] tabsaisie = {jTextFieldDenominationNomSociete,jTextFieldDenominationIdentifiant, jTextFieldAdresseNumeroRue,jTextFieldAdresseComplement,
            jTextFieldAdresseCP,jTextFieldAdresseVille, jTextFieldAdresseCedex,jTextFieldContactNom,
                jTextFieldContactPrenom,jTextFieldContactTelephone1,jTextFieldContactTelephone2,jTextFieldContactFax,
                    jTextFieldContactMail, jTextFieldComplementSiret, jTextFieldComplementRepresentant, jTextFieldComplementSalaireFixeBrut, jTextFieldComplementTauxDeCommission,
                        jTextFieldDerniereProspectionDate, jTextFieldInformationCommercialeCommande};
        for (JTextField tabsaisie1 : tabsaisie) {
            tabsaisie1.setEditable(false);
        }
        
        //Cache le panel Complément (SIRET & Représentant)
        jPanelComplementClientProspect.setVisible(false); 
        jPanelDerniereProspection.setVisible(false);
        jPanelInformationCommerciale.setVisible(false);
        
        
        //Cache les boutons Enregister et Modifier
        jButtonEnregister.setVisible(false);
        jButtonAnnuler.setVisible(false);
        
        //Cache les listes Clients et Prospects
        jScrollPaneClient.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFond = new javax.swing.JPanel();
        jPanelDenomination = new javax.swing.JPanel();
        jLabelDenominationNomSociete = new javax.swing.JLabel();
        jTextFieldDenominationNomSociete = new javax.swing.JTextField();
        jTextFieldDenominationIdentifiant = new javax.swing.JTextField();
        jLabelDenominationIdentifiant = new javax.swing.JLabel();
        jPaneAdresse = new javax.swing.JPanel();
        jTextFieldAdresseNumeroRue = new javax.swing.JTextField();
        jLabelAdresseNumeroRue = new javax.swing.JLabel();
        jLabelAdresseComplement = new javax.swing.JLabel();
        jTextFieldAdresseComplement = new javax.swing.JTextField();
        jTextFieldAdresseCedex = new javax.swing.JTextField();
        jTextFieldAdresseVille = new javax.swing.JTextField();
        jTextFieldAdresseCP = new javax.swing.JTextField();
        jLabelAdresseCPVilleCedex = new javax.swing.JLabel();
        jLabelAdressePays = new javax.swing.JLabel();
        jComboBoxPays = new javax.swing.JComboBox<>();
        jPanelContact = new javax.swing.JPanel();
        jTextFieldContactNom = new javax.swing.JTextField();
        jLabelContactNom = new javax.swing.JLabel();
        jLabelContactPrenom = new javax.swing.JLabel();
        jLabeContactTelephone = new javax.swing.JLabel();
        jLabelContactFax = new javax.swing.JLabel();
        jLabelContactMail = new javax.swing.JLabel();
        jTextFieldContactMail = new javax.swing.JTextField();
        jTextFieldContactFax = new javax.swing.JTextField();
        jTextFieldContactTelephone1 = new javax.swing.JTextField();
        jTextFieldContactTelephone2 = new javax.swing.JTextField();
        jTextFieldContactPrenom = new javax.swing.JTextField();
        jPanelComplementRepresentant = new javax.swing.JPanel();
        jLabelComplementTauxDeCommission = new javax.swing.JLabel();
        jLabelComplementSalaireFixeBrut = new javax.swing.JLabel();
        jTextFieldComplementTauxDeCommission = new javax.swing.JTextField();
        jTextFieldComplementSalaireFixeBrut = new javax.swing.JTextField();
        jLabelComplementTauxDeCommissionPourcent = new javax.swing.JLabel();
        jLabelComplementSalaireFixeBrutEuro = new javax.swing.JLabel();
        jPanelComplementClientProspect = new javax.swing.JPanel();
        jLabelComplementSiret = new javax.swing.JLabel();
        jTextFieldComplementSiret = new javax.swing.JTextField();
        jTextFieldComplementRepresentant = new javax.swing.JTextField();
        jLabelComplementRepresentant = new javax.swing.JLabel();
        jPanelInformationCommerciale = new javax.swing.JPanel();
        jTextFieldInformationCommercialeCommande = new javax.swing.JTextField();
        jLabelInformationCommercialeCommande = new javax.swing.JLabel();
        jPanelDerniereProspection = new javax.swing.JPanel();
        jLabelDerniereProspectionDate = new javax.swing.JLabel();
        jTextFieldDerniereProspectionDate = new javax.swing.JTextField();
        jButtonModifier = new javax.swing.JButton();
        jButtonAjouter = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        jButtonFermer = new javax.swing.JButton();
        jButtonEnregister = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        jScrollPaneClient = new javax.swing.JScrollPane();
        jTableClient = new javax.swing.JTable();
        jScrollPaneRepresentant = new javax.swing.JScrollPane();
        jTableRepresentant = new javax.swing.JTable();
        jScrollPaneProspect = new javax.swing.JScrollPane();
        jTableProspect = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuRepresentant = new javax.swing.JMenu();
        jMenuClient = new javax.swing.JMenu();
        jMenuProspect = new javax.swing.JMenu();
        jMenuImprimer = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Toutbois - Représsentants - Clients - Prospects");
        setResizable(false);
        setSize(new java.awt.Dimension(800, 900));

        jPanelFond.setLayout(null);

        jPanelDenomination.setBorder(javax.swing.BorderFactory.createTitledBorder("Dénomination"));
        jPanelDenomination.setOpaque(false);

        jLabelDenominationNomSociete.setText("Nom");

        jTextFieldDenominationNomSociete.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDenominationNomSocieteFocusLost(evt);
            }
        });
        jTextFieldDenominationNomSociete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDenominationNomSocieteActionPerformed(evt);
            }
        });

        jTextFieldDenominationIdentifiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDenominationIdentifiantActionPerformed(evt);
            }
        });

        jLabelDenominationIdentifiant.setText("Id. représentant");

        javax.swing.GroupLayout jPanelDenominationLayout = new javax.swing.GroupLayout(jPanelDenomination);
        jPanelDenomination.setLayout(jPanelDenominationLayout);
        jPanelDenominationLayout.setHorizontalGroup(
            jPanelDenominationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDenominationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDenominationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDenominationNomSociete)
                    .addComponent(jLabelDenominationIdentifiant, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanelDenominationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDenominationNomSociete, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDenominationIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelDenominationLayout.setVerticalGroup(
            jPanelDenominationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDenominationLayout.createSequentialGroup()
                .addGroup(jPanelDenominationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDenominationNomSociete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDenominationNomSociete))
                .addGap(18, 18, 18)
                .addGroup(jPanelDenominationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDenominationIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDenominationIdentifiant))
                .addGap(39, 39, 39))
        );

        jPanelFond.add(jPanelDenomination);
        jPanelDenomination.setBounds(10, 20, 385, 120);

        jPaneAdresse.setBorder(javax.swing.BorderFactory.createTitledBorder("Adresse"));

        jTextFieldAdresseNumeroRue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAdresseNumeroRueFocusLost(evt);
            }
        });
        jTextFieldAdresseNumeroRue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAdresseNumeroRueActionPerformed(evt);
            }
        });

        jLabelAdresseNumeroRue.setText("N° et rue");

        jLabelAdresseComplement.setText("Complément");

        jTextFieldAdresseCedex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAdresseCedexActionPerformed(evt);
            }
        });

        jLabelAdresseCPVilleCedex.setText("CP Ville Cedex");

        jLabelAdressePays.setText("Pays");

        jComboBoxPays.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "France", "Allemagne", "Autriche", "Belgique", "Bulgarie", "Chypre", "Croatie", "Danemark", "Espagne", "Estonie", "Finlande", "Grèce", "Hongrie", "Irlande", "Italie", "Lituanie", "Lettonie", "Luxembourg", "Malte", "Pays-Bas", "Pologne", "Portugal", "République tchèque", "Roumanie", "Royaume-Uni", "Slovaquie", "Slovénie", "Suède" }));
        jComboBoxPays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPaysActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneAdresseLayout = new javax.swing.GroupLayout(jPaneAdresse);
        jPaneAdresse.setLayout(jPaneAdresseLayout);
        jPaneAdresseLayout.setHorizontalGroup(
            jPaneAdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneAdresseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneAdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneAdresseLayout.createSequentialGroup()
                        .addGroup(jPaneAdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAdresseComplement)
                            .addComponent(jLabelAdresseNumeroRue))
                        .addGap(27, 27, 27)
                        .addGroup(jPaneAdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAdresseComplement, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAdresseNumeroRue, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPaneAdresseLayout.createSequentialGroup()
                        .addGroup(jPaneAdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAdresseCPVilleCedex)
                            .addComponent(jLabelAdressePays))
                        .addGap(18, 18, 18)
                        .addGroup(jPaneAdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPaneAdresseLayout.createSequentialGroup()
                                .addComponent(jTextFieldAdresseCP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldAdresseVille, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldAdresseCedex, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxPays, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
        );
        jPaneAdresseLayout.setVerticalGroup(
            jPaneAdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneAdresseLayout.createSequentialGroup()
                .addGroup(jPaneAdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdresseNumeroRue)
                    .addComponent(jTextFieldAdresseNumeroRue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPaneAdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdresseComplement)
                    .addComponent(jTextFieldAdresseComplement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPaneAdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdresseCPVilleCedex)
                    .addComponent(jTextFieldAdresseCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAdresseVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAdresseCedex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPaneAdresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdressePays)
                    .addComponent(jComboBoxPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        jPanelFond.add(jPaneAdresse);
        jPaneAdresse.setBounds(10, 150, 385, 210);

        jPanelContact.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact"));

        jLabelContactNom.setText("Nom");

        jLabelContactPrenom.setText("Prénom");

        jLabeContactTelephone.setText("Téléphone");

        jLabelContactFax.setText("Fax");

        jLabelContactMail.setText("E-Mail");

        jTextFieldContactTelephone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContactTelephone2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelContactLayout = new javax.swing.GroupLayout(jPanelContact);
        jPanelContact.setLayout(jPanelContactLayout);
        jPanelContactLayout.setHorizontalGroup(
            jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContactLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelContactLayout.createSequentialGroup()
                            .addComponent(jLabeContactTelephone)
                            .addGap(36, 36, 36)
                            .addComponent(jTextFieldContactTelephone1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldContactTelephone2))
                        .addGroup(jPanelContactLayout.createSequentialGroup()
                            .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelContactFax)
                                .addComponent(jLabelContactMail))
                            .addGap(61, 61, 61)
                            .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldContactFax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldContactMail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelContactLayout.createSequentialGroup()
                        .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelContactPrenom)
                            .addComponent(jLabelContactNom))
                        .addGap(53, 53, 53)
                        .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldContactPrenom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldContactNom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );
        jPanelContactLayout.setVerticalGroup(
            jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContactLayout.createSequentialGroup()
                .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContactNom)
                    .addComponent(jTextFieldContactNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContactPrenom)
                    .addComponent(jTextFieldContactPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeContactTelephone)
                    .addComponent(jTextFieldContactTelephone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldContactTelephone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContactFax)
                    .addComponent(jTextFieldContactFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContactMail)
                    .addComponent(jTextFieldContactMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanelFond.add(jPanelContact);
        jPanelContact.setBounds(10, 370, 385, 260);

        jPanelComplementRepresentant.setBorder(javax.swing.BorderFactory.createTitledBorder("Complément"));

        jLabelComplementTauxDeCommission.setText("Taux de commission");

        jLabelComplementSalaireFixeBrut.setText("Salaire fixe brut");

        jLabelComplementTauxDeCommissionPourcent.setText("%");

        jLabelComplementSalaireFixeBrutEuro.setText("€");

        javax.swing.GroupLayout jPanelComplementRepresentantLayout = new javax.swing.GroupLayout(jPanelComplementRepresentant);
        jPanelComplementRepresentant.setLayout(jPanelComplementRepresentantLayout);
        jPanelComplementRepresentantLayout.setHorizontalGroup(
            jPanelComplementRepresentantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComplementRepresentantLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelComplementRepresentantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelComplementSalaireFixeBrut)
                    .addComponent(jLabelComplementTauxDeCommission))
                .addGap(140, 140, 140)
                .addGroup(jPanelComplementRepresentantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldComplementSalaireFixeBrut, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldComplementTauxDeCommission, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelComplementRepresentantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelComplementTauxDeCommissionPourcent)
                    .addComponent(jLabelComplementSalaireFixeBrutEuro))
                .addGap(40, 40, 40))
        );
        jPanelComplementRepresentantLayout.setVerticalGroup(
            jPanelComplementRepresentantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComplementRepresentantLayout.createSequentialGroup()
                .addGroup(jPanelComplementRepresentantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldComplementTauxDeCommission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelComplementTauxDeCommissionPourcent)
                    .addComponent(jLabelComplementTauxDeCommission))
                .addGap(18, 18, 18)
                .addGroup(jPanelComplementRepresentantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelComplementSalaireFixeBrut)
                    .addComponent(jTextFieldComplementSalaireFixeBrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelComplementSalaireFixeBrutEuro))
                .addGap(39, 39, 39))
        );

        jPanelFond.add(jPanelComplementRepresentant);
        jPanelComplementRepresentant.setBounds(405, 20, 385, 120);

        jPanelComplementClientProspect.setBorder(javax.swing.BorderFactory.createTitledBorder("Complément"));

        jLabelComplementSiret.setText("SIRET");

        jLabelComplementRepresentant.setText("Représentant");

        javax.swing.GroupLayout jPanelComplementClientProspectLayout = new javax.swing.GroupLayout(jPanelComplementClientProspect);
        jPanelComplementClientProspect.setLayout(jPanelComplementClientProspectLayout);
        jPanelComplementClientProspectLayout.setHorizontalGroup(
            jPanelComplementClientProspectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComplementClientProspectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelComplementClientProspectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelComplementSiret)
                    .addComponent(jLabelComplementRepresentant))
                .addGap(23, 23, 23)
                .addGroup(jPanelComplementClientProspectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldComplementSiret, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldComplementRepresentant, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        jPanelComplementClientProspectLayout.setVerticalGroup(
            jPanelComplementClientProspectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComplementClientProspectLayout.createSequentialGroup()
                .addGroup(jPanelComplementClientProspectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelComplementSiret)
                    .addComponent(jTextFieldComplementSiret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelComplementClientProspectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelComplementRepresentant)
                    .addComponent(jTextFieldComplementRepresentant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jPanelFond.add(jPanelComplementClientProspect);
        jPanelComplementClientProspect.setBounds(405, 20, 385, 120);

        jPanelInformationCommerciale.setBorder(javax.swing.BorderFactory.createTitledBorder("Informations commerciales"));

        jLabelInformationCommercialeCommande.setText("Commandes");

        javax.swing.GroupLayout jPanelInformationCommercialeLayout = new javax.swing.GroupLayout(jPanelInformationCommerciale);
        jPanelInformationCommerciale.setLayout(jPanelInformationCommercialeLayout);
        jPanelInformationCommercialeLayout.setHorizontalGroup(
            jPanelInformationCommercialeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInformationCommercialeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInformationCommercialeCommande)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jTextFieldInformationCommercialeCommande, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelInformationCommercialeLayout.setVerticalGroup(
            jPanelInformationCommercialeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformationCommercialeLayout.createSequentialGroup()
                .addGroup(jPanelInformationCommercialeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInformationCommercialeCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInformationCommercialeCommande))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        jPanelFond.add(jPanelInformationCommerciale);
        jPanelInformationCommerciale.setBounds(405, 150, 385, 75);

        jPanelDerniereProspection.setBorder(javax.swing.BorderFactory.createTitledBorder("Dernière prospection"));

        jLabelDerniereProspectionDate.setText("Date");

        jTextFieldDerniereProspectionDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDerniereProspectionDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDerniereProspectionLayout = new javax.swing.GroupLayout(jPanelDerniereProspection);
        jPanelDerniereProspection.setLayout(jPanelDerniereProspectionLayout);
        jPanelDerniereProspectionLayout.setHorizontalGroup(
            jPanelDerniereProspectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDerniereProspectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDerniereProspectionDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jTextFieldDerniereProspectionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelDerniereProspectionLayout.setVerticalGroup(
            jPanelDerniereProspectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDerniereProspectionLayout.createSequentialGroup()
                .addGroup(jPanelDerniereProspectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDerniereProspectionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDerniereProspectionDate))
                .addGap(27, 27, 27))
        );

        jPanelFond.add(jPanelDerniereProspection);
        jPanelDerniereProspection.setBounds(405, 150, 385, 75);

        jButtonModifier.setText("Modifier");
        jButtonModifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonModifierMouseClicked(evt);
            }
        });
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });
        jPanelFond.add(jButtonModifier);
        jButtonModifier.setBounds(300, 785, 90, 23);

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAjouterMouseClicked(evt);
            }
        });
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });
        jPanelFond.add(jButtonAjouter);
        jButtonAjouter.setBounds(200, 785, 90, 23);

        jButtonSupprimer.setText("Supprimer");
        jPanelFond.add(jButtonSupprimer);
        jButtonSupprimer.setBounds(400, 785, 90, 23);

        jButtonFermer.setText("Fermer");
        jButtonFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFermerActionPerformed(evt);
            }
        });
        jPanelFond.add(jButtonFermer);
        jButtonFermer.setBounds(500, 785, 90, 23);

        jButtonEnregister.setText("Enregister");
        jButtonEnregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEnregisterMouseClicked(evt);
            }
        });
        jButtonEnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnregisterActionPerformed(evt);
            }
        });
        jPanelFond.add(jButtonEnregister);
        jButtonEnregister.setBounds(510, 600, 90, 23);

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });
        jPanelFond.add(jButtonAnnuler);
        jButtonAnnuler.setBounds(610, 600, 90, 23);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LogoTronconeuse.png"))); // NOI18N
        jPanelFond.add(jLabelLogo);
        jLabelLogo.setBounds(430, 220, 385, 385);

        jTableClient.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTableClient.setModel(tbP);
        jTableClient.getTableHeader().setReorderingAllowed(false);
        jScrollPaneClient.setViewportView(jTableClient);

        jPanelFond.add(jScrollPaneClient);
        jScrollPaneClient.setBounds(10, 640, 780, 130);

        jTableRepresentant.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTableRepresentant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Identifiant", "Nom", "Ville", "Fixe brut", "Taux com."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableRepresentant.getTableHeader().setReorderingAllowed(false);
        jScrollPaneRepresentant.setViewportView(jTableRepresentant);

        jPanelFond.add(jScrollPaneRepresentant);
        jScrollPaneRepresentant.setBounds(10, 640, 780, 130);

        jTableProspect.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTableProspect.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Identifiant", "Enseigne", "Ville", "Derniére visite le", "Représentant"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProspect.getTableHeader().setReorderingAllowed(false);
        jScrollPaneProspect.setViewportView(jTableProspect);

        jPanelFond.add(jScrollPaneProspect);
        jScrollPaneProspect.setBounds(10, 640, 780, 130);

        jMenuRepresentant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/technicalsupportrepresentative_male_dark_32.png"))); // NOI18N
        jMenuRepresentant.setText("Représentant");
        jMenuRepresentant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuRepresentantMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuRepresentant);

        jMenuClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/folder_customer_32.png"))); // NOI18N
        jMenuClient.setText("Client");
        jMenuClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuClientMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuClient);

        jMenuProspect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/telephone_32.png"))); // NOI18N
        jMenuProspect.setText("Prospect");
        jMenuProspect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuProspectMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuProspect);

        jMenuImprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/print_32.png"))); // NOI18N
        jMenuImprimer.setText("Imprimer");
        jMenuImprimer.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jMenuImprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuImprimerMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuImprimer);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFond, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFond, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldContactTelephone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContactTelephone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContactTelephone2ActionPerformed

    private void jMenuRepresentantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuRepresentantMouseClicked
        // TODO add your handling code here:
        jLabelDenominationNomSociete.setText("Nom");
        jLabelDenominationIdentifiant.setText("Id. représentant");
        jPanelComplementClientProspect.setVisible(false);
        jPanelComplementRepresentant.setVisible(true);
        jPanelDerniereProspection.setVisible(false);
        //Cache les listes Clients et Prospects et affiche la liste Representant
        jScrollPaneClient.setVisible(false);
        jScrollPaneRepresentant.setVisible(true);
        jScrollPaneProspect.setVisible(false);
        jPanelInformationCommerciale.setVisible(false);
        
        //Affichage en gras du menu affiché "Représentant" et mise en non-gras des 2 autres
        jMenuRepresentant.setFont(new Font("default", Font.BOLD,12));
        jMenuClient.setFont(new Font("default", Font.PLAIN,12));
        jMenuProspect.setFont(new Font("default", Font.PLAIN,12));
        
        infoMenu = 'r';
        System.out.println("Menu = "+ infoMenu);
    }//GEN-LAST:event_jMenuRepresentantMouseClicked

    private void jMenuClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuClientMouseClicked
        // TODO add your handling code here:
        jLabelDenominationNomSociete.setText("Enseigne");
        jLabelDenominationIdentifiant.setText("Id. client");
        jPanelComplementClientProspect.setVisible(true);
        jPanelComplementRepresentant.setVisible(false);
        jPanelDerniereProspection.setVisible(false);
        
        //Affiche la liste des Clients et cache les listes Representant et Prospect
        jScrollPaneClient.setVisible(true);
        jScrollPaneRepresentant.setVisible(false);
        jScrollPaneProspect.setVisible(false);
        jPanelInformationCommerciale.setVisible(true);
        
        //Affichage en gras du menu affiché "Client" et mise en non-gras des 2 autres
        jMenuRepresentant.setFont(new Font("default", Font.PLAIN,12));
        jMenuClient.setFont(new Font("default", Font.BOLD,12));
        jMenuProspect.setFont(new Font("default", Font.PLAIN,12));
        
        infoMenu = 'c';
        System.out.println("Menu = "+ infoMenu);
    }//GEN-LAST:event_jMenuClientMouseClicked

    private void jMenuProspectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuProspectMouseClicked
        // TODO add your handling code here:
        jLabelDenominationNomSociete.setText("Enseigne");
        jLabelDenominationIdentifiant.setText("Id. prospect");
        jPanelComplementClientProspect.setVisible(true);
        jPanelComplementRepresentant.setVisible(false);
        jPanelDerniereProspection.setVisible(true);
        
        //Affiche la liste des Prospect et cache les listes Clients et Représentant
        jScrollPaneClient.setVisible(false);
        jScrollPaneRepresentant.setVisible(false);
        jScrollPaneProspect.setVisible(true);
        jPanelInformationCommerciale.setVisible(false);
        
        
        //Affichage en gras du menu affiché "Prospect" et mise en non-gras des 2 autres
        jMenuRepresentant.setFont(new Font("default", Font.PLAIN,12));
        jMenuClient.setFont(new Font("default", Font.PLAIN,12));
        jMenuProspect.setFont(new Font("default", Font.BOLD,12));
        
        infoMenu = 'p';
        System.out.println("Menu = "+ infoMenu);
    }//GEN-LAST:event_jMenuProspectMouseClicked

    private void jButtonAjouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAjouterMouseClicked

    }//GEN-LAST:event_jButtonAjouterMouseClicked

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        // TODO add your handling code here:
        
        //Lorsque l'on clique sur ajouter : on vide tous les champs  ET les rend modifiable sauf jTextFieldDenominationIdentifiant (Identifiant) etjTextFieldInformationCommercialeCommande
        JTextField[] tabsaisie = {jTextFieldDenominationNomSociete, jTextFieldAdresseNumeroRue,jTextFieldAdresseComplement,
            jTextFieldAdresseCP,jTextFieldAdresseVille, jTextFieldAdresseCedex,jTextFieldContactNom,
                jTextFieldContactPrenom,jTextFieldContactTelephone1,jTextFieldContactTelephone2,jTextFieldContactFax,
                    jTextFieldContactMail, jTextFieldComplementSiret, jTextFieldComplementRepresentant, jTextFieldComplementSalaireFixeBrut, jTextFieldComplementTauxDeCommission,
                        jTextFieldDerniereProspectionDate};
       
        for (JTextField tabsaisie1 : tabsaisie) {
            tabsaisie1.setText("");
            tabsaisie1.setEditable(true);            
        }
        
        //Affiche les boutons Enregister et Annuler
        jButtonEnregister.setVisible(true);
        jButtonAnnuler.setVisible(true);
          
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jButtonFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFermerActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        int option = JOptionPane.showConfirmDialog(null, "Voulez-vous fermer cette fenêtre?", "Fermer?",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            //Si "Oui" :
            if (option == JOptionPane.OK_OPTION) {
                //fermer en libérant les ressources
                this.dispose();
            }
    }//GEN-LAST:event_jButtonFermerActionPerformed

    private void jTextFieldAdresseCedexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAdresseCedexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAdresseCedexActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        // TODO add your handling code here:
        //Lorsque l'on clique sur modifier  on rend les champs modifiable sauf jTextFieldDenominationIdentifiant (Identifiant) et jTextFieldInformationCommercialeCommande
        JTextField[] tabsaisie = {jTextFieldDenominationNomSociete, jTextFieldAdresseNumeroRue,jTextFieldAdresseComplement,
            jTextFieldAdresseCP,jTextFieldAdresseVille, jTextFieldAdresseCedex,jTextFieldContactNom,
                jTextFieldContactPrenom,jTextFieldContactTelephone1,jTextFieldContactTelephone2,jTextFieldContactFax,
                    jTextFieldContactMail, jTextFieldComplementSiret, jTextFieldComplementRepresentant, jTextFieldComplementSalaireFixeBrut, jTextFieldComplementTauxDeCommission,
                        jTextFieldDerniereProspectionDate};
       
        for (JTextField tabsaisie1 : tabsaisie) {
            tabsaisie1.setEditable(true);            
        }
        
        //Affiche les boutons Enregister et Annuler
        jButtonEnregister.setVisible(true);
        jButtonAnnuler.setVisible(true);
        
        
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonModifierMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonModifierMouseClicked

    private void jTextFieldDenominationNomSocieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDenominationNomSocieteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDenominationNomSocieteActionPerformed

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        // TODO add your handling code here:
        
       //Ouverture d'une fenetre de confirmation "Quitter sans sauvegarde"       
        int option = JOptionPane.showConfirmDialog(null, "Voulez-vous quitter sans sauvegarder ?", "Quitter sans sauvegarde?",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            //Si "Oui" :
            if (option == JOptionPane.OK_OPTION) {
                //Rend les champs non modifiable
                JTextField[] tabsaisie = {jTextFieldDenominationNomSociete,jTextFieldDenominationIdentifiant, jTextFieldAdresseNumeroRue,jTextFieldAdresseComplement,
                    jTextFieldAdresseCP,jTextFieldAdresseVille, jTextFieldAdresseCedex,jTextFieldContactNom,
                        jTextFieldContactPrenom,jTextFieldContactTelephone1,jTextFieldContactTelephone2,jTextFieldContactFax,
                            jTextFieldContactMail, jTextFieldComplementSiret, jTextFieldComplementRepresentant, jTextFieldComplementSalaireFixeBrut, jTextFieldComplementTauxDeCommission
                                , jTextFieldInformationCommercialeCommande};
                for (JTextField tabsaisie1 : tabsaisie) {
                    tabsaisie1.setEditable(false);
                }
                //Cache les boutons Enregister et Annuler
                jButtonEnregister.setVisible(false);
                jButtonAnnuler.setVisible(false);
            }

        
        
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    private void jTextFieldDerniereProspectionDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDerniereProspectionDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDerniereProspectionDateActionPerformed

    private void jButtonEnregisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEnregisterMouseClicked
        // TODO add your handling code here:
        //String menu = Character.toString(infoMenu);
        String chaineSaisi = "";
        chaineSaisi = jTextFieldDenominationNomSociete.getText()+ " " + jTextFieldDenominationIdentifiant.getText()+" " + jTextFieldAdresseNumeroRue.getText()+ " " + jTextFieldAdresseComplement.getText()+" " +
            jTextFieldAdresseCP.getText()+" " +jTextFieldAdresseVille.getText()+" " + jTextFieldAdresseCedex.getText()+" " +jComboBoxPays.getSelectedItem()+" " +jTextFieldContactNom.getText()+" " +
                jTextFieldContactPrenom.getText()+" " +jTextFieldContactTelephone1.getText()+" " +jTextFieldContactTelephone2.getText()+" " +jTextFieldContactFax.getText()+" " +
                    jTextFieldContactMail.getText()+" " + jTextFieldComplementSiret.getText()+" " + jTextFieldComplementRepresentant.getText()+" " + jTextFieldComplementSalaireFixeBrut.getText()+" " +jTextFieldContactMail.getText()+" " + jTextFieldComplementSiret.getText()+" " + jTextFieldComplementRepresentant.getText()+" " + jTextFieldComplementSalaireFixeBrut.getText()+" " + jTextFieldComplementTauxDeCommission.getText()+ " " +jTextFieldComplementTauxDeCommission.getText()+" " +
                         jTextFieldInformationCommercialeCommande.getText();
       
        LectureEcritureFichierTxt lef = new LectureEcritureFichierTxt();
        lef.ecritureClient(chaineSaisi);
        
        
        /*Client client1 = new Client(jTextFieldDenominationNomSociete.getText(), jTextFieldDenominationIdentifiant.getText(), jTextFieldAdresseNumeroRue.getText() ,jTextFieldAdresseComplement.getText(), 
            jTextFieldAdresseCP.getText(),jTextFieldAdresseVille.getText(), jTextFieldAdresseCedex.getText(),jComboBoxPays.getSelectedItem().toString(),jTextFieldContactNom.getText(),
                jTextFieldContactPrenom.getText(),jTextFieldContactTelephone1.getText(),jTextFieldContactTelephone2.getText(),jTextFieldContactFax.getText(),
                    jTextFieldContactMail.getText());*/
        
        
    }//GEN-LAST:event_jButtonEnregisterMouseClicked

    private void jButtonEnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnregisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEnregisterActionPerformed

    private void jTextFieldDenominationIdentifiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDenominationIdentifiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDenominationIdentifiantActionPerformed

    private void jTextFieldAdresseNumeroRueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAdresseNumeroRueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAdresseNumeroRueActionPerformed

    private void jComboBoxPaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPaysActionPerformed

    private void jMenuImprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuImprimerMouseClicked
        // TODO add your handling code here:
        
        String menu = Character.toString(infoMenu);
        //Mets les champs de la fiche dans un tableau apres les avoir convertit en String
        String tabChaineSaisie[] = { jTextFieldDenominationNomSociete.getText(), jTextFieldDenominationIdentifiant.getText(),
            jTextFieldAdresseNumeroRue.getText(), jTextFieldAdresseComplement.getText(), jTextFieldAdresseCP.getText(),
            jTextFieldAdresseVille.getText(), jTextFieldAdresseCedex.getText(),jComboBoxPays.getSelectedItem().toString(),
            jTextFieldContactNom.getText(), jTextFieldContactPrenom.getText(),jTextFieldContactTelephone1.getText(),
            jTextFieldContactTelephone2.getText(),jTextFieldContactFax.getText(),jTextFieldContactMail.getText(), 
            jTextFieldComplementSiret.getText(), jTextFieldComplementRepresentant.getText(),
            jTextFieldComplementSalaireFixeBrut.getText(), jTextFieldComplementTauxDeCommission.getText(),
            jTextFieldInformationCommercialeCommande.getText(), jTextFieldDerniereProspectionDate.getText(), menu};
        
        
        //Méthode imprimer de Impression
        Impression fiche = new Impression();
        fiche.imprimer(tabChaineSaisie);
    }//GEN-LAST:event_jMenuImprimerMouseClicked

    private void jTextFieldDenominationNomSocieteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDenominationNomSocieteFocusLost
        // TODO add your handling code here:

        //Méthode de controle saisie (2 < longueur champ < 30)
        ControleSaisie ctrl = new ControleSaisie();
        ctrl.setLongueur(jTextFieldDenominationNomSociete.getText().length());
        ctrl.ctrlLongueur();
        
        //Mets le texte du label en rouge si condition non remplie
        if (!ctrl.isValidationLongueur()) {
            jLabelDenominationNomSociete.setForeground(Color.red);
            /*Border borderRed = BorderFactory.createLineBorder(Color.red);
            jTextFieldDenominationNomSociete.setBorder(borderRed);*/
        } else {
            jLabelDenominationNomSociete.setForeground(Color.black);
            /*Border borderEmpty = BorderFactory.createEmptyBorder();
            jTextFieldDenominationNomSociete.setBorder(borderEmpty);*/
        }

    }//GEN-LAST:event_jTextFieldDenominationNomSocieteFocusLost

    private void jTextFieldAdresseNumeroRueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAdresseNumeroRueFocusLost
        // TODO add your handling code here:
        ControleSaisie ctrl = new ControleSaisie();
        ctrl.setLongueur(jTextFieldAdresseNumeroRue.getText().length());
        ctrl.ctrlNonVide();
        
        //Mets le texte du label en rouge si condition non remplie
        if (!ctrl.isValidationNonVide()) {
            jLabelAdresseNumeroRue.setForeground(Color.red);
        } else {
            jLabelAdresseNumeroRue.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextFieldAdresseNumeroRueFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RepCliProspOLD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RepCliProspOLD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RepCliProspOLD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RepCliProspOLD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RepCliProspOLD dialog = new RepCliProspOLD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonEnregister;
    private javax.swing.JButton jButtonFermer;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JComboBox<String> jComboBoxPays;
    private javax.swing.JLabel jLabeContactTelephone;
    private javax.swing.JLabel jLabelAdresseCPVilleCedex;
    private javax.swing.JLabel jLabelAdresseComplement;
    private javax.swing.JLabel jLabelAdresseNumeroRue;
    private javax.swing.JLabel jLabelAdressePays;
    private javax.swing.JLabel jLabelComplementRepresentant;
    private javax.swing.JLabel jLabelComplementSalaireFixeBrut;
    private javax.swing.JLabel jLabelComplementSalaireFixeBrutEuro;
    private javax.swing.JLabel jLabelComplementSiret;
    private javax.swing.JLabel jLabelComplementTauxDeCommission;
    private javax.swing.JLabel jLabelComplementTauxDeCommissionPourcent;
    private javax.swing.JLabel jLabelContactFax;
    private javax.swing.JLabel jLabelContactMail;
    private javax.swing.JLabel jLabelContactNom;
    private javax.swing.JLabel jLabelContactPrenom;
    private javax.swing.JLabel jLabelDenominationIdentifiant;
    private javax.swing.JLabel jLabelDenominationNomSociete;
    private javax.swing.JLabel jLabelDerniereProspectionDate;
    private javax.swing.JLabel jLabelInformationCommercialeCommande;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClient;
    private javax.swing.JMenu jMenuImprimer;
    private javax.swing.JMenu jMenuProspect;
    private javax.swing.JMenu jMenuRepresentant;
    private javax.swing.JPanel jPaneAdresse;
    private javax.swing.JPanel jPanelComplementClientProspect;
    private javax.swing.JPanel jPanelComplementRepresentant;
    private javax.swing.JPanel jPanelContact;
    private javax.swing.JPanel jPanelDenomination;
    private javax.swing.JPanel jPanelDerniereProspection;
    private javax.swing.JPanel jPanelFond;
    private javax.swing.JPanel jPanelInformationCommerciale;
    private javax.swing.JScrollPane jScrollPaneClient;
    private javax.swing.JScrollPane jScrollPaneProspect;
    private javax.swing.JScrollPane jScrollPaneRepresentant;
    private javax.swing.JTable jTableClient;
    private javax.swing.JTable jTableProspect;
    private javax.swing.JTable jTableRepresentant;
    private javax.swing.JTextField jTextFieldAdresseCP;
    private javax.swing.JTextField jTextFieldAdresseCedex;
    private javax.swing.JTextField jTextFieldAdresseComplement;
    private javax.swing.JTextField jTextFieldAdresseNumeroRue;
    private javax.swing.JTextField jTextFieldAdresseVille;
    private javax.swing.JTextField jTextFieldComplementRepresentant;
    private javax.swing.JTextField jTextFieldComplementSalaireFixeBrut;
    private javax.swing.JTextField jTextFieldComplementSiret;
    private javax.swing.JTextField jTextFieldComplementTauxDeCommission;
    private javax.swing.JTextField jTextFieldContactFax;
    private javax.swing.JTextField jTextFieldContactMail;
    private javax.swing.JTextField jTextFieldContactNom;
    private javax.swing.JTextField jTextFieldContactPrenom;
    private javax.swing.JTextField jTextFieldContactTelephone1;
    private javax.swing.JTextField jTextFieldContactTelephone2;
    private javax.swing.JTextField jTextFieldDenominationIdentifiant;
    private javax.swing.JTextField jTextFieldDenominationNomSociete;
    private javax.swing.JTextField jTextFieldDerniereProspectionDate;
    private javax.swing.JTextField jTextFieldInformationCommercialeCommande;
    // End of variables declaration//GEN-END:variables
}
